{{- if .Values.mysql.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: {{ .Values.mysql.storage }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/mysql"
{{- end }}
