apiVersion: v1
kind: Service
metadata:
  name: mysql-exporter
  labels:
    app: mysql
    release: kube-prometheus
spec:
  selector:
    app: mysql
  ports:
    - name: metrics
      port: 9104
      targetPort: 9104
