fastapi:
  enabled: true
  image: gunjan/fastapi-app:v2
  replicaCount: 1
  servicePort: 8000
  resources:
    requests:
      cpu: "100m"
    limits:
      cpu: "200m"
  sidecar:
    enabled: true
    name: log-sidecar
    image: busybox
    command: ["sh", "-c", "tail -n+1 -F /app/logs/app.log"]

mysql:
  enabled: true
  rootPassword: root
  database: testdb
  storage: 1Gi

ingress:
  enabled: true
  host: fastapi.local
