name: Helm Chart CI

on:
  push:
    branches:
      - main
    paths:
      - 'fastapi-chart/**'
  workflow_dispatch:

jobs:
  helm-lint-and-package:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: v3.13.3

    - name: Helm Lint
      run: helm lint fastapi-chart

    - name: Helm Package
      run: |
        mkdir -p artifacts
        helm package fastapi-chart --destination artifacts

    - name: Upload Helm Chart Artifact
      uses: actions/upload-artifact@v3
      with:
        name: fastapi-chart-package
        path: artifacts/*.tgz

